baseURL: https://sliverhorn.com
languageCode: zh-CN
title: SliverHorn的博客
theme: maupassant-hugo
googleAnalytics: ""
preserveTaxonomyNames: true
disablePathToLower: true
hasCJKLanguage: true
summaryLength: 140
author:
  name: SliverHorn
params:
  author: SliverHorn
  subtitle: Golang 开发
  keywords: >
    golang,SliverHorn,gin-vue-admin,gf-vue-admin
  description: 一个Gopher开源爱好者
  busuanzi: true
  googleAd: ""
  localSearch: true
  beian: 粤ICP备19128176号
  fancybox: true
  customCSS:
    - douban.css
    - other.css
  customJS:
    - douban.js
  toc: true
  links:
    -
      title: 榨汁
      name: 榨汁
      url: https://www.squeeze-juice.cn/
    -
      title: 牛逼哄哄 `王哥` 博客
      name: 牛逼哄哄 `王哥` 博客
      url: https://blog.leonardwang.cn/
    -
      title: songzhibin97的博客
      name: songzhibin97的博客
      url: https://www.cnblogs.com/binHome/
    -
      title: 跃动指尖 – 悦动生活
      name: 跃动指尖 – 悦动生活
      url: https://leixf.cn/
    -
      title: 术习电报
      name: 术习电报
      url: https://www.treesystem.cn
  ads:
  utteranc:
    enable: true
    repo: your github repo
    issueTerm: pathname
    theme: github-light
  cc:
    name: >
      知识共享署名-非商业性使用-禁止演绎
      4.0 国际许可协议
    link: >
      https://creativecommons.org/licenses/by-nc-nd/4.0/
  seeAlso: 0
markup:
  highlight:
    lineNos: true
    style: github
menu:
  main:
    -
      identifier: linux
      name: linux
      url: /linux/
      weight: 1
    -
      identifier: operating_system
      name: 操作系统
      url: /operating_system/
      weight: 2
    -
      identifier: tool
      name: 工具
      url: /tool/
      weight: 3
    -
      identifier: archives
      name: 归档
      url: /archives/
      weight: 4
    -
      identifier: about
      name: 关于
      url: /about/
      weight: 5
