baseURL: https://sliverhorn.com
languageCode: zh-CN
title: SliverHorn的博客
theme: maupassant-hugo
googleAnalytics: ""
preserveTaxonomyNames: true
disablePathToLower: true
hasCJKLanguage: true
summaryLength: 140
author:
  name: SliverHorn
params:
  author: SliverHorn
  subtitle: Golang 开发
  keywords: >
    golang,SliverHorn,gin-vue-admin,gf-vue-admin
  description: 一个Gopher开源爱好者
  busuanzi: true
  googleAd: ""
  localSearch: true
  beian: 粤ICP备19128176号
  fancybox: true
  customCSS:
    - douban.css
    - other.css
  customJS:
    - douban.js
  toc: true
  links:
    - 
      title: 牛逼哄哄 `王哥` 博客
      name: 牛逼哄哄 `王哥` 博客
      url: https://blog.leonardwang.cn/
    - 
      title: songzhibin97的博客
      name: songzhibin97的博客
      url: https://www.cnblogs.com/binHome/
  ads:
  utteranc:
    enable: true
    repo: your github repo
    issueTerm: pathname
    theme: github-light
  cc:
    name: >
      知识共享署名-非商业性使用-禁止演绎
      4.0 国际许可协议
    link: >
      https://creativecommons.org/licenses/by-nc-nd/4.0/
markup:
  highlight:
    lineNos: true
    style: github
menu:
  main:
    - 
      identifier: tool
      name: 工具
      url: /tool/
      weight: 1
    - 
      identifier: archives
      name: 归档
      url: /archives/
      weight: 2
    - 
      identifier: about
      name: 关于
      url: /about/
      weight: 6